name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Utiliser un runner Windows

    steps:
      # Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Vérifier la syntaxe HTML
      - name: Check HTML syntax
        run: |
          choco install htmlhint
          htmlhint index.html

      # Vérifier la syntaxe CSS
      - name: Check CSS syntax
        run: |
          choco install csslint
          csslint style.css

      # Déployer sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .  # Déploie la racine du dépôt
